### ISSUE TITLE
Potential security risk in Password Reset functionality

### ISSUE THREAD

**Issue by sudokim** [sudokim/skku-web-chat#9]
The password reset dialog prompts the user whether the email address is valid or not.
`This email doesn't exist / Password reset link sent`
This might be dangerous because a malicious user can use this to check if an email address is being used in this app.

It would be safer to prompt the user like:
`We will send you a password reset link if your email address is valid` regardless of the validity of the email address.

**Comment by wikiverse** [comment]
I initially implemented it the way you mentioned, but Reset Password functionality alerts the user by email, so if someone tries to guess your email address, you can simply make your password stronger. On top of that, there is a limit to how many times you can request the link.

From a user's perspective, I think it would be a hassle to wait for a never-coming email, if they don't know if they created an account in the first place.

Many other social media sites also tell if a certain email is connected to an account on their websites (like Discord). A good argument to this is that they have 2FA so that they send a sign-in verification email in order to check if it's the real user and save their browser for next time.

Therefore, let's implement a passwordless sign-in.

**Comment by sudokim** [comment]
Will be fixed in #10.
